### ISSUE TITLE
Feature Request: make .properties ERB enabled

### ISSUE THREAD

**Issue by tk8817** [getgauge/gauge-ruby#33]
Hey folks, 

I love the idea of the default.properties, however it would be great if it were ERB enabled such that settings can by dynamically driven based on execution context.

**Comment by sriv** [comment]
Hey - I am a bit confused.

Did you mean having a `default.properties.erb` which will get compiled to `default.properties` on project initialization?

Or would you like to have a `default.properties.erb` which gauge-ruby would extrapolate at execution time?

In either case, could you provide some details on how this would help? 

cheers

**Comment by tk8817** [comment]
Hi @sriv , thanks for the quick response - I think there is a disconnect in the request. There is no need to change the file extension and this would be something that happens on runtime rather than initialization. 

Many ruby libraries 'erb enable' certain files, usually to do with configuration, such that config values can be dynamically set on each run. A good example is cucumber.yml for cucumber & calabash. 

To give an example for Gauge, imagine you want to dynamically set the report directory on runtime based on your current environment, and if no value is provided by the user, use some default path.

with erb we could do this to the default.properties file

```
# default.properties
# properties set here will be available to the test execution as environment variables

# sample_key = sample_value

#The path to the gauge reports directory. Should be either relative to the project directory or an absolute path
gauge_reports_dir = <%= ENV['REPORT_DIR'] || reports  %>

#Set as false if gauge reports should not be overwritten on each execution. A new time-stamped directory will be created on each execution.
overwrite_reports = true
```

When the default.properties file is read in by Gauge, it gets processed for ERB which turns that ruby code into a result and you will be left with either the value of ENV['REPORT_DIR'] or 'reports'.

**Comment by sriv** [comment]
@tk8817 - thanks for the explanation. This helps. 

So, the way Gauge works is that at runtime, it scans all the relevant properties files, and generates a map of key->value. This is all done by Gauge Core. It then sets the environment variables from this map and invokes that language runner (in this case, gauge-ruby), thereby passing the env variables.

Now, Gauge Core is common across all languages Gauge supports, and erb is ruby specific(?). Hence if we were to implement this, it has to be consistent across all languages that Gauge supports.

This also means that the properties files are read and utilized before gauge-ruby process begins.

One way to do this is to rescan and set properties file in ruby and expand them

**Comment by tk8817** [comment]
Ahhhhh, interesting that the core handles this - very cool. In that case, 100% this would never work, we will just continue to set our configs in our spec_helper.rb :) No problem at all, default.properties just looked like a really nice place to do this. 

Best,
J

**Comment by xgraffm** [comment]
Would it be possible to access the report dir property in some scope within the ruby instance to change the path to something generated programmatically?

Example
spec_helper.rb
##mock file content
....
@timestamp = Time.now.to_s.gsub(" ", "-").gsub(":","_")
...
def timestamp
  return @timestamp
end
report_dir = "/var/tmp/reports/#{timestamp}"
...
before_scenario (or other relevant scope)
#ruby instance properties
 properties["gauge_report_path"] = report_path 
end
...
## mock end

If this were possible, I could store a report with associated files in a single temporary location.  I do this now for screenshots and other capture files (like page diffs generated by diffy).  I then pass the file paths to jira-ruby as jira attachments.  Since the "/var/tmp/timestamp" directory is a timestamp, I reduce chance of overwriting, can safely attach all files from that location and set a cronjob to clean up relevant contents of /var/tmp periodically.  

Thanks.

**Comment by nehashri** [comment]
@xgraffm Unfortunately, this is not possible. 
When Gauge starts off execution, the ruby plugin and all other plugins are started off simultaneously.
The reporting plugin is responsible for the report creations. 
Since, there is no communication between the ruby plugin and reporting plugin, changing the report path during runtime is impossible.
