### ISSUE TITLE
Install gauge-ruby gem at execution time if not already installed for that particular gemset.

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge-ruby#4]

**Comment by navaneeth** [comment]
Don't do this now. There are bigger changes needed for Ruby runner. Will draft a detailed email about this

**Comment by sriv** [comment]
Would it help to just put the `gauge-ruby` gem in rubygems.org? That way we let bundler/rvm take care of  managing the gem install?

Something to consider, rvm does not work out of cygwin in windows.

**Comment by navaneeth** [comment]
These are my thoughts on fixing gauge-ruby so that it can be used easily

Once gauge-ruby gem is installed into one gemset, switching to other will complain about the absence of gauge-ruby. There is no way to force the install. When running `gauge --install ruby` it says already installed. 

The other problem is since gauge-ruby is installed as a stand-alone gem and not part of the bundle, `rake` tasks won't have access to it. Which means, starting gauge through a rake task is not possible. If it is pushed to rubygems.org, users can add it to `Gemfile` which will make it part of bundle and available for all `rake` tasks.

Proposed solution:

* Push gauge-ruby to rubygems.org
* Write a gauge-rails gem which will add necessary rake tasks to the current project so that rake tasks are readily available
* `Gauge specs` can also check the availability of gem and force a gem install so that non rvm managed environments will work fine
* `gauge --init ruby` or `gauge --install ruby` can add `gauge-ruby` gem to the Gemfile if a Gemfile is present. 

I can write the gauge-rails gem once it is pushed to rubugems.org

Thoughts?

**Comment by sriv** [comment]
+1 to having gauge-ruby in rubygems.org. Just that I'd like it called
`gauge` instead of `gauge-ruby`. I agree that having bundler do what it
does best, would save a lot of headache for us.

**Comment by sriv** [comment]
The gem is now available here - https://rubygems.org/gems/gauge-ruby.

Am closing this issue, the gauge-rails support can be tracked via #8.

**Comment by navaneeth** [comment]
That's perfect.
